//! `.vellis/agent-inbox.md` generator (`docs/ai-collab.md` §4.3).
//!
//! Pure formatting only — file I/O lives in `AnnotationStore::write_inbox`
//! so the canonical path guard is exercised in one place.

use std::fmt::Write as _;

use super::types::Mark;

/// HTML comment banner placed at the top of the inbox.
fn banner() -> String {
    format!(
        "<!-- generated by vellis {} — do not edit by hand -->",
        env!("CARGO_PKG_VERSION")
    )
}

const PROLOGUE: &str = "\
# Markdown Review Instructions

You are reviewing Markdown files in this repository. For each instruction \
below, modify the referenced file in place. Do not change file paths, \
heading structure, or sections that are not referenced.

When you finish, run no other actions. The reviewer (vellis) detects \
file changes and shows the diff.
";

const TRAILER: &str = "\n<!-- end -->\n";

/// Format the inbox Markdown for the given marks.  Output is
/// deterministic for the same input slice.
pub fn format_inbox(marks: &[Mark]) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{}", banner());
    out.push_str(PROLOGUE);

    for mark in marks {
        out.push('\n');
        let _ = writeln!(out, "## {}", mark.id);
        let _ = writeln!(out, "- File: `{}`", mark.file);
        let _ = writeln!(
            out,
            "- Lines: {}-{}",
            mark.anchor.start_line, mark.anchor.end_line
        );
        if !mark.anchor.heading_path.is_empty() {
            let _ = writeln!(out, "- Heading: {}", mark.anchor.heading_path.join(" > "));
        }
        out.push_str("- Selected:\n");
        let fence = pick_fence(&mark.anchor.selected_markdown);
        let _ = writeln!(out, "  {}", fence);
        for line in mark.anchor.selected_markdown.lines() {
            let _ = writeln!(out, "  {}", line);
        }
        let _ = writeln!(out, "  {}", fence);
        out.push_str("- Instruction:\n");
        for line in mark.instruction.lines() {
            let _ = writeln!(out, "  {}", line);
        }
    }

    out.push_str(TRAILER);
    out
}

/// Pick a tilde fence whose length exceeds the longest run of tildes in
/// `content`.  Always at least 4 to keep simple cases consistent
/// (`docs/ai-collab.md` §4.3 — Codeblock-Adaptive Fence).
fn pick_fence(content: &str) -> String {
    let max_run = max_consecutive(content, '~');
    let len = std::cmp::max(4, max_run + 1);
    "~".repeat(len)
}

fn max_consecutive(s: &str, ch: char) -> usize {
    let mut max = 0usize;
    let mut cur = 0usize;
    for c in s.chars() {
        if c == ch {
            cur += 1;
            if cur > max {
                max = cur;
            }
        } else {
            cur = 0;
        }
    }
    max
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::annotation::types::{Anchor, Mark};

    fn mark(file: &str, headings: Vec<&str>, selected: &str, instruction: &str) -> Mark {
        let mut m = Mark::new(
            file.into(),
            Anchor {
                start_line: 10,
                end_line: 12,
                start_offset: 0,
                end_offset: 0,
                selected_text: selected.into(),
                selected_markdown: selected.into(),
                heading_path: headings.into_iter().map(String::from).collect(),
                context_before: "".into(),
                context_after: "".into(),
                file_hash: "h".into(),
            },
            instruction.into(),
        );
        // Stable id for snapshot tests
        m.id = crate::annotation::types::MarkId("mark_01TESTID".into());
        m
    }

    #[test]
    fn banner_includes_crate_version() {
        let b = banner();
        assert!(b.contains(env!("CARGO_PKG_VERSION")));
        assert!(b.starts_with("<!--"));
        assert!(b.ends_with("-->"));
    }

    #[test]
    fn empty_marks_produces_just_banner_prologue_and_trailer() {
        let out = format_inbox(&[]);
        assert!(out.contains("# Markdown Review Instructions"));
        assert!(out.contains("<!-- end -->"));
    }

    #[test]
    fn single_mark_section_has_required_fields() {
        let m = mark(
            "docs/spec.md",
            vec!["API", "認証"],
            "現在の仕様では...",
            "最新仕様に合わせて修正",
        );
        let out = format_inbox(&[m]);
        assert!(out.contains("## mark_01TESTID"));
        assert!(out.contains("- File: `docs/spec.md`"));
        assert!(out.contains("- Lines: 10-12"));
        assert!(out.contains("- Heading: API > 認証"));
        assert!(out.contains("- Selected:"));
        assert!(out.contains("  現在の仕様では..."));
        assert!(out.contains("- Instruction:"));
        assert!(out.contains("  最新仕様に合わせて修正"));
        assert!(out.ends_with("<!-- end -->\n"));
    }

    #[test]
    fn heading_line_omitted_when_path_is_empty() {
        let m = mark("a.md", vec![], "x", "y");
        let out = format_inbox(&[m]);
        assert!(!out.contains("- Heading:"));
    }

    #[test]
    fn fence_is_default_four_tildes_when_content_has_no_runs() {
        let m = mark("a.md", vec![], "plain text", "fix");
        let out = format_inbox(&[m]);
        assert!(out.contains("  ~~~~\n  plain text\n  ~~~~\n"));
    }

    #[test]
    fn fence_bumps_when_content_contains_four_tildes() {
        let m = mark("a.md", vec![], "before\n~~~~\nmid\n~~~~\nafter", "fix");
        let out = format_inbox(&[m]);
        assert!(out.contains("  ~~~~~\n"));
        assert!(!out.matches("  ~~~~\n").count() > 0 || out.contains("  ~~~~~\n"));
    }

    #[test]
    fn fence_bumps_when_content_contains_five_tildes() {
        let m = mark("a.md", vec![], "~~~~~\nbody", "fix");
        let out = format_inbox(&[m]);
        assert!(out.contains("  ~~~~~~\n"));
    }

    #[test]
    fn multiline_selection_is_indented_per_line() {
        let m = mark("a.md", vec![], "line1\nline2\nline3", "fix");
        let out = format_inbox(&[m]);
        assert!(out.contains("  line1\n  line2\n  line3\n"));
    }

    #[test]
    fn multiline_instruction_is_indented_per_line() {
        let m = mark("a.md", vec![], "x", "step 1\nstep 2");
        let out = format_inbox(&[m]);
        assert!(out.contains("  step 1\n  step 2\n"));
    }

    #[test]
    fn multiple_marks_are_separated_by_blank_line() {
        let m1 = mark("a.md", vec!["A"], "ax", "fix a");
        let mut m2 = mark("b.md", vec!["B"], "bx", "fix b");
        m2.id = crate::annotation::types::MarkId("mark_02TESTID".into());
        let out = format_inbox(&[m1, m2]);
        // Order preserved
        let pos_a = out.find("mark_01TESTID").unwrap();
        let pos_b = out.find("mark_02TESTID").unwrap();
        assert!(pos_a < pos_b);
    }

    #[test]
    fn max_consecutive_helper() {
        assert_eq!(max_consecutive("", '~'), 0);
        assert_eq!(max_consecutive("abc", '~'), 0);
        assert_eq!(max_consecutive("~", '~'), 1);
        assert_eq!(max_consecutive("~~~", '~'), 3);
        assert_eq!(max_consecutive("a~~b~~~c~", '~'), 3);
        assert_eq!(max_consecutive("a~~~~~b", '~'), 5);
    }
}
